MESSAGES = {
     # Subscription Messages
    "UNEXPECTED_ERROR": "An unexpected error occurred.",
    "STRIPE_ERROR": "Stripe Error",
    "PRODUCT_RETRIVED" : "Products retrieved successfully",
    "FIELDS_MISSING" : "Product ID, Username and Email are required",
    "REQUIRED_FIELDS" : "Missing required fields",
    "USER_FIELDS_ERROR" : "User Email and Product IDs are required",
    "MISSING_IDS" : "Missing User Email or Product IDs",
    "PRODUCT_NOT_FOUND" : "Product not found",
    "PRODUCT_ID_MISSING" : "Product with the given ID does not exist",
    "SESSION_GENERATED" : "Gateway Session Created Successfully",
    "PRICE_FIELD_NOT_FOUND" : "No Default Price Found for the Product",
    "PRICE_NOT_FOUND" : "Product does not have a Default Price",
    "CUSTOMER_FOUND" : "Customers retrieved successfully.",
    "CUSTOMER_NOT_FOUND" : "Customers Unavailable",
    "UNAVAILABLE_CUSTOMERS" : "There are no customers available",
    "STRIPE_API_ERROR"  : "Stripe API Error",
    "INVALID_FORMAT": "Invalid List Format",
    "MISSING_FIELDS" : "Required Missing Fields",
    "FIELDS_NOT_AVAILABLE" : "user_id, product_id, and community_ids are required",
    "INVALID_ID_FORMAT": "Invalid product_ids Format",
    "INVALID_PRODUCT_ID_FORMAT" : "product_id format not supported",
    "INVALID_UUID": "Invalid UUID Format",
    "INVALID_UUID_FORMAT" : "Invalid UUID format for one or more community_ids.",
    "SUBSCRIPTION_ERROR" : "One or more community_ids are invalid or have a status that doesn't allow subscription",
    "METADATA_ERROR":"MISSING METADATA",
    "INVALID_COMMUNITY_ID" :"Invalid community_id format",
    "MISSING_ID":"Missing community_id or user_id",
    "USER_NOT_FOUND":"User not found",
    "COMMUNITY_ERROR":"One or more communities not found",
    "INVALID_COMMUNITY_STATUS": "Invalid community status",
    "INVALID_SUBSCRIPTION_ID" : "Invalid subscription",
    "SUBSCRIPTION_PLAN_FETCHED": "Subscription Plan Fetched successfully",
    "SUBSCRIPTION_CANCELLATION_SUCCESS": "Subscription Cancelled successfully",
    "ALREADY_ACTIVE_FREE_TRIAL": "Already Active Free",
    "THIS_PRODUCT_IS_NOT_FREE": "This Product is not a Trail Product",
    "FREE_TRIAL_SUBSCRIPTION_SESSION_CREATED": "Free Transactions Session Created",
    "SUBSCRIPTIONS_FOUND": "Subscriptions Found",
    "REVENUE_CALCULATED": "Revenue Fetched",
}